### ISSUE TITLE
Doesn't get output file with version above or equal 9.0

### ISSUE THREAD

**Issue by MichaelChen77** [mkazhdan/PoissonRecon#93]
Hi,

I run the PoissionRecon in the cmd.exe. The command line is "PoissonRecon --in bunny.points.ply --out bunny.ply --depth 10 --pointWeight 0", and the .ply file is bunny.points.ply from your website http://www.cs.jhu.edu/~misha/Code/PoissonRecon/Version10.05. 

Now the situation is that if I execute the command line with PoissionRecon.exe with version 7.0 or 8.0, it works. And I can get the output file.
If I execute the command line with PoissionRecon.exe with version 9.0 or above(such as 9.01, 10.0, 10.01, 10.02 and so on), it seems to works but without any output. The reason I use "seems" is because it took a little time to execute this command line but obviously shorter than the workable version 7.0 and 8.0 took.

My system is windows 10,

Could you please give me some solution? Thanks!

**Comment by MichaelChen77** [comment]
Thanks for the quick reply!
Yes, the "output" means bunny.ply file in my situation. This file wasn't generated via the PoissionRecon.exe with version 9.0 or above. Here I took version 10.05 and 8.0 as examples, and the output to the screen is following:

//10.05 without bunny.ply file being generated
D:\test>PoissonRecon_10.05 --in bunny.points.ply --out bunny.ply --depth 10 --pointWeight 0 --verbose
*************************************************************
*************************************************************
** Running Screened Poisson Reconstruction (Version 10.05) **
*************************************************************
*************************************************************
        --in bunny.points.ply
        --depth 10
        --out bunny.ply
        --verbose
        --pointWeight 0.000000
Input Points / Samples: 362271 / 352410
# Read input into tree:       0.6 (s),     146.1 (MB) /     146.1 (MB) /       0.0 (MB)
![screenshot 2](https://user-images.githubusercontent.com/31195921/51322529-a19cad00-1aa0-11e9-88ce-027daa9be447.png)

//8.0 with bunny.ply file being generated
D:\test>PoissonRecon_8.0 --in bunny.points.ply --out bunny.ply --depth 10 --pointWeight 0 --verbose
Running Screened Poisson Reconstruction (Version 8.0)
        --in bunny.points.ply
        --depth 10
        --out bunny.ply
        --verbose
        --pointWeight 0.000000
#             Tree set in:       3.2 (s),     214.3 (MB)
Input Points: 362271
Leaves/Nodes: 3951256/4515721
Memory Usage: 293.543 MB
#      Constraints set in:       2.1 (s),     333.9 (MB)
Memory Usage: 246.059 MB
Depth[0/9]: 8
        Evaluated / Got / Solved in:  0.000 /  0.000 /  0.000   (271.055 MB)
Depth[1/9]: 64
        Evaluated / Got / Solved in:  0.000 /  0.000 /  0.000   (271.059 MB)
Depth[2/9]: 512
        Evaluated / Got / Solved in:  0.000 /  0.000 /  0.000   (271.063 MB)
Depth[3/9]: 4096
        Evaluated / Got / Solved in:  0.000 /  0.000 /  0.000   (271.063 MB)
Depth[4/9]: 32768
        Evaluated / Got / Solved in:  0.000 /  0.016 /  0.000   (273.199 MB)
Depth[5/9]: 262144
        Evaluated / Got / Solved in:  0.000 /  0.088 /  0.019   (273.082 MB)
Depth[6/9]: 100648
        Evaluated / Got / Solved in:  0.000 /  0.094 /  0.047   (284.605 MB)
Depth[7/9]: 375872
        Evaluated / Got / Solved in:  0.000 /  0.218 /  0.220   (289.340 MB)
Depth[8/9]: 1223544
        Evaluated / Got / Solved in:  0.000 /  0.686 /  0.547   (293.168 MB)
Depth[9/9]: 2516064
        Evaluated / Got / Solved in:  0.000 /  1.294 /  1.025   (292.504 MB)
# Linear system solved in:       4.5 (s),     293.2 (MB)
Memory Usage: 250.422 MB
Got average in: 0.219000
Iso-Value: 5.873893e-001
#        Got triangles in:       3.6 (s),     237.9 (MB)
#             Total Solve:      13.6 (s),     333.9 (MB)
Vertices / Polygons: 684401 / 1368798
![screenshot 4](https://user-images.githubusercontent.com/31195921/51322633-efb1b080-1aa0-11e9-8191-c9086958f462.png)

//end

**Comment by mkazhdan** [comment]
Very strange. Could it be a write permission issue? Also, can you run with --performance as well? (That does some final command line output, so if you see it, that means the code didn't crash.)

**Comment by mkazhdan** [comment]
Very strange indeed. Did you recompile the binaries or use the ones provided?

**Comment by MichaelChen77** [comment]
The above 2 PoissonRecon.exe file are provided from website "http://www.cs.jhu.edu/~misha/Code/PoissonRecon/Version10.05/" and "http://www.cs.jhu.edu/~misha/Code/PoissonRecon/Version8.0/" separately.

According to your suggestion, I also downloaded these 2 versions' source code and compile them separetely with Visual Studio 2017 on my laptop. Both of them generated PoissonRecon.exe successfully. But for version 8.0, I have to add "#define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS 1" in many source files to make it build successfully.

However, the result is that both of these generated PoissonRecon.exe don't work. Please kindly see the screenshots following:
![screenshot 7](https://user-images.githubusercontent.com/31195921/51326128-65ba1580-1aa9-11e9-9c14-562a62bbaebd.png)

**Comment by mkazhdan** [comment]
This is very strange indeed, and I have never seen anything like it before.
Do you see similar issues with the other pointsets
The only thing I could recommend would be trying to debug things to see where the code is crashing. But that would be highly non-trivial, given the complexity of the code.

**Comment by MichaelChen77** [comment]
I am sorry for the late reply.
This morning I double checked it again. 

As for the other pointsets(For example, eagle.points from your website), the result is similar, only the "provided PoissionRecon of version 8.0/7.0" work. All "generated  PoissionRecon" and  "provided PoissionRecon of version above or equal 9.0" don't work.

I am going to try to debug the code today, will update if I found anything strange.

Thanks for the kindly advice!

**Comment by mkazhdan** [comment]
Please let me know if you come up with something. I'm very surprised by this behavior.

**Comment by roby23** [comment]
I have the same problem. I tried to debug and I get an exception in the file FEMTree.System.inl, function _setMatrixRowAndGetConstraintFromProlongation, line 923:

`row[count++] = MatrixEntry< Real >( nodeIndex-offset , (Real)( _values[ WindowIndex< OverlapSizes , OverlapRadii >::Index ] + _stencil[ WindowIndex< OverlapSizes , OverlapRadii >::Index ] ) );`

Exception thrown at 0x00007FF72AA1186D in SSDRecon.exe: 0xC0000005: Access violation writing location 0x0000000000026930.

I get this exception only if I use depth > 9

**Comment by mkazhdan** [comment]
Can you share the dataset and parameters you used when getting the exception? Also, which OS was this under?

**Comment by roby23** [comment]
The OS is Windows 10. Here is the point cloud

[full.zip](https://github.com/mkazhdan/PoissonRecon/files/2836429/full.zip)

I tried both PoissonRecon and SSDRecon:

PoissonRecon.exe --in full.ply --out mesh.ply --depth 10

SSDRecon.exe --in full.ply --out mesh.ply --depth 10

**Comment by mkazhdan** [comment]
Thanks for sharing the data.
There was indeed a bug that was causing memory to be deallocated when it was still needed.
The bug has been fixed in the recently posted Version 10.07 .

**Comment by csyhping** [comment]
Hi,
I've tried the 10.07 version but I still get no output file. Here is the screen capture, could you please give me some help? Thank you.
![捕获](https://user-images.githubusercontent.com/38368516/55205900-a358be80-520f-11e9-8dd1-c6bca0615901.PNG)

**Comment by mkazhdan** [comment]
It definitely looks like the code is crashing, though I have not been able to reproduce the problem. Can you try running with the additional parameter "--threads 1"?

**Comment by csyhping** [comment]
> It definitely looks like the code is crashing, though I have not been able to reproduce the problem. Can you try running with the additional parameter "--threads 1"?

Here is the screen capture, still no output file. By the way, as @MichaelChen77 said, version 8.0 works well but version 10.x fails.
![捕获](https://user-images.githubusercontent.com/38368516/55209836-80cea180-521f-11e9-84b0-cb85c6e55e7b.PNG)

**Comment by mkazhdan** [comment]
Just out of curiosity, have you tried version 11?

**Comment by csyhping** [comment]
> Just out of curiosity, have you tried version 11?

Same problem, no output(I tried with/without `--threads 1)`
![捕获](https://user-images.githubusercontent.com/38368516/55229407-db83ef80-5257-11e9-9c64-05b7f2233c63.PNG)

**Comment by mkazhdan** [comment]
Hmm. I'm assuming you get the same problem when you don't set the point weight to zero. 

Unfortunately, this is hard to debug as I cannot reproduce the problem on my windows machine. Are you compiling the code yourself? If so, you can try to define the preprocessor flag ARRAY_DEBUG. It might provide more information about the error. Also, if you're compiling with MSVC you can try to run the code through the debugger to see where the code is crashing.

**Comment by csyhping** [comment]
> Hmm. I'm assuming you get the same problem when you don't set the point weight to zero.
> 
> Unfortunately, this is hard to debug as I cannot reproduce the problem on my windows machine. Are you compiling the code yourself? If so, you can try to define the preprocessor flag ARRAY_DEBUG. It might provide more information about the error. Also, if you're compiling with MSVC you can try to run the code through the debugger to see where the code is crashing.

I complied the code but the exe still fails, with debug it shows the following info. Do you have and idea with it?
![微信截图_20190330103847](https://user-images.githubusercontent.com/38368516/55270300-378e5880-52d8-11e9-89cc-2101fe51feaf.png)

**Comment by mkazhdan** [comment]
Very strange. It's hard to guess why there is an illegal instruction there. Any chance you can query the value of d? (It could be case that, somehow, it's bigger than 64 and the system is complaining you can't represent numbers that large.
